baseURL = "https://dturner.cloud/"
languageCode = "en-us"
title = "Declan Turner | DevOps"
theme = "m10c"
googleAnalytics = "G-05MC70WMFB"
[menu]
	[[menu.main]]
		identifier = "home"
		name = "Home"
		url = "/"
		weight = 1
	[[menu.main]]
		identifier = "about"
		name = "About"
		url = "/about/"
		weight = 2

[params]
	name = "dturner.cloud"
	author = "Declan Turner"
	description = "My ramblings on things Cloud, DevOps or Tech related"
	avatar = "/avatar.png"
	[[params.social]]
		icon = "linkedin"
		name = "LinkedIn"
		url = "https://linkedin.com/in/declan-turner-devops"
	[[params.social]]
		icon = "github"
		name = "GitHub"
		url = "https://github.com/DTGitRepository"

#	[[params.style]]
#		darkestColor = "#315659"
#		darkColor = "#253031"
#		lightColor = "#96a879"
#		lightestColor = "#fff"
#		primaryColor = "#dad865"
